# Form implementation generated from reading ui file '.\FileExplorer.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 68)
        Form.setStyleSheet("QWidget#Form{\n"
"    background-color: rgba(56, 60, 72, 90);\n"
"    border-radius: 10px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputpath = QtWidgets.QTextEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputpath.sizePolicy().hasHeightForWidth())
        self.inputpath.setSizePolicy(sizePolicy)
        self.inputpath.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.inputpath.setFont(font)
        self.inputpath.setStyleSheet("QTextEdit{\n"
"border-radius: 8px;\n"
"border: 2px solid rgb(0, 85, 127);\n"
"background-color: rgba(255, 255, 255, 150);\n"
"color: rgb(56, 60, 72);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QTextEdit:focus{\n"
"border-radius: 8px;\n"
"border: 2px solid rgb(19, 148, 207);\n"
"background-color: rgba(255, 255, 255, 190);\n"
"padding: 2px;\n"
"}")
        self.inputpath.setObjectName("inputpath")
        self.horizontalLayout.addWidget(self.inputpath)
        self.browsebtn = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsebtn.sizePolicy().hasHeightForWidth())
        self.browsebtn.setSizePolicy(sizePolicy)
        self.browsebtn.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.browsebtn.setFont(font)
        self.browsebtn.setStyleSheet("QPushButton#browsebtn{\n"
"border-radius: 8px;\n"
"border: 2px solid rgb(0, 85, 127);\n"
"background-color: rgba(255, 255, 255, 150);\n"
"color: rgb(0, 170, 255);\n"
"padding: 2px;\n"
"}\n"
"\n"
"QPushButton#browsebtn:hover{\n"
"border-radius: 8px;\n"
"border: 2px solid rgb(19, 148, 207);\n"
"background-color: rgba(255, 255, 255, 190);\n"
"color: rgb(38, 197, 255);\n"
"padding: 2px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons_w/res/feather (1)/folder.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.browsebtn.setIcon(icon)
        self.browsebtn.setIconSize(QtCore.QSize(20, 20))
        self.browsebtn.setObjectName("browsebtn")
        self.horizontalLayout.addWidget(self.browsebtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.browsebtn.setText(_translate("Form", "Buscar"))
