# Form implementation generated from reading ui file '.\slidemenu_button.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class slidemenu_btn(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 50)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(240, 50))
        Form.setMaximumSize(QtCore.QSize(240, 50))
        Form.setStyleSheet("QWidget{\n"
"background-color: rgb(56, 60, 72);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QWidget:hover{\n"
"    background-color: rgb(144, 155, 186);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.itgstatusindicator = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itgstatusindicator.sizePolicy().hasHeightForWidth())
        self.itgstatusindicator.setSizePolicy(sizePolicy)
        self.itgstatusindicator.setMinimumSize(QtCore.QSize(15, 15))
        self.itgstatusindicator.setMaximumSize(QtCore.QSize(15, 15))
        self.itgstatusindicator.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(38, 225, 54);")
        self.itgstatusindicator.setObjectName("itgstatusindicator")
        self.horizontalLayout.addWidget(self.itgstatusindicator)
        self.button = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setMinimumSize(QtCore.QSize(210, 32))
        self.button.setMaximumSize(QtCore.QSize(210, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.button.setFont(font)
        self.button.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;")
        self.button.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.button.setCheckable(False)
        self.button.setAutoRepeat(False)
        self.button.setAutoExclusive(False)
        self.button.setObjectName("button")
        self.horizontalLayout.addWidget(self.button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "NAME"))
