# Form implementation generated from reading ui file '.\FileExplorerTree.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys

class TreeFileExplorer(QtWidgets.QMainWindow):
    
    def __init__(self):
        super(TreeFileExplorer, self).__init__()
        self.treeView = None
        self.centralwg = QtWidgets.QWidget(parent=self)
        self.setCentralWidget(self.centralwg)
        self.setupUi(self.centralwg)
        self.dragging = False
        self.moving_offset = QtCore.QPoint(0,0)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 437)
        Form.setStyleSheet("QWidget{\n"
"border-radius: 8px;\n"
"background-color: rgba(255, 255, 255, 130);\n"
"padding: 2px;\n"
"}\n"
"QWidget#Form{\n"
"background-color: rgb(56, 60, 72);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setStyleSheet("QWidget{\n"
"border-top: 2px solid rgb(19, 148, 207);\n"
"border-bottom: 2px solid rgb(19, 148, 207);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-top: none;\n"
"border-bottom: none;\n"
"border-right: 2px solid rgb(85, 170, 255);\n"
"border-left: 2px solid rgb(85, 170, 255);\n"
"background-color: rgba(233, 247, 255, 180);\n"
"padding: 0px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.desktopBtn = QtWidgets.QPushButton(parent=self.widget)
        self.desktopBtn.setMinimumSize(QtCore.QSize(0, 35))
        self.desktopBtn.setObjectName("desktopBtn")
        self.horizontalLayout_2.addWidget(self.desktopBtn)
        self.selectBtn = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.selectBtn.setObjectName("selectBtn")
        self.horizontalLayout_2.addWidget(self.selectBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"background: transparent;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtWidgets.QTreeView(parent=self.widget_2)
        self.treeView.setStyleSheet("border: 2px solid rgb(19, 148, 207);")
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))
        self.desktopBtn.setText(_translate("Form", "Move To Desktop"))
        self.selectBtn.setText(_translate("Form", "Select"))

    def mousePressEvent(self, event: QtGui.QMouseEvent):
        if event.button() == QtCore.Qt.MouseButton.LeftButton:
            self.dragging = True
            self.moving_offset = event.pos().toPointF().toPoint()
            event.accept()

    def mouseReleaseEvent(self, event: QtGui.QMouseEvent):
        if event.button() == QtCore.Qt.MouseButton.LeftButton:
            self.dragging = False
            event.accept()

    def mouseMoveEvent(self, event: QtGui.QMouseEvent):
        if self.dragging:  #
            self.move(self.pos().x().real + (event.pos().x().real - self.moving_offset.x().real),
                              self.pos().y().real + (event.pos().y().real - self.moving_offset.y().real))
            event.accept()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = TreeFileExplorer()
    Form.show()
    sys.exit(app.exec())