# Form implementation generated from reading ui file '.\FileExplorer.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class FileBrowserWidget(QtWidgets.QWidget):

    def __init__(self):
        super(FileBrowserWidget, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 68)
        Form.setStyleSheet("QWidget#Form{\n"
                           "    background-color: rgba(56, 60, 72, 90);\n"
                           "    border-radius: 10px;\n"
                           "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputpath = QtWidgets.QTextEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputpath.sizePolicy().hasHeightForWidth())
        self.inputpath.setSizePolicy(sizePolicy)
        self.inputpath.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.inputpath.setFont(font)
        self.inputpath.setStyleSheet("QTextEdit{\n"
                                     "border-radius: 8px;\n"
                                     "border: 2px solid rgb(0, 85, 127);\n"
                                     "background-color: rgba(255, 255, 255, 150);\n"
                                     "color: rgb(56, 60, 72);\n"
                                     "padding: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QTextEdit:focus{\n"
                                     "border-radius: 8px;\n"
                                     "border: 2px solid rgb(19, 148, 207);\n"
                                     "background-color: rgba(255, 255, 255, 190);\n"
                                     "padding: 2px;\n"
                                     "}")
        self.inputpath.setObjectName("inputpath")
        self.horizontalLayout.addWidget(self.inputpath)
        self.browsebtn = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsebtn.sizePolicy().hasHeightForWidth())
        self.browsebtn.setSizePolicy(sizePolicy)
        self.browsebtn.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        self.browsebtn.setFont(font)
        self.browsebtn.setStyleSheet("QPushButton#browsebtn{\n"
                                     "border-radius: 8px;\n"
                                     "border: 2px solid rgb(0, 85, 127);\n"
                                     "background-color: rgba(255, 255, 255, 150);\n"
                                     "color: rgb(0, 170, 255);\n"
                                     "padding: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton#browsebtn:hover{\n"
                                     "border-radius: 8px;\n"
                                     "border: 2px solid rgb(19, 148, 207);\n"
                                     "background-color: rgba(255, 255, 255, 190);\n"
                                     "color: rgb(38, 197, 255);\n"
                                     "padding: 2px;\n"
                                     "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/res/feather (1)/folder.svg"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        self.browsebtn.setIcon(icon)
        self.browsebtn.setIconSize(QtCore.QSize(20, 20))
        self.browsebtn.setObjectName("browsebtn")
        self.horizontalLayout.addWidget(self.browsebtn)

        self.browsebtn.clicked.connect(self.openFileExplorer)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def openFileExplorer(self):
        exp = TreeFileExplorer(self)
        exp.show()
        exp.showFullScreen()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.browsebtn.setText(_translate("Form", "Buscar"))


class TreeFileExplorer(QtWidgets.QDialog):

    def __init__(self, widg):
        super(TreeFileExplorer, self).__init__()
        self.resize(700, 800)
        self.browserWidget = widg
        self.centralwg = QtWidgets.QWidget(parent=self)
        #self.setCentralWidget(self.centralwg)
        self.setupUi(self.centralwg)
        self.dragging = False
        self.moving_offset = QtCore.QPoint(0, 0)
        self.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 437)
        Form.setStyleSheet("QWidget{\n"
                           "border-radius: 8px;\n"
                           "background-color: rgba(255, 255, 255, 130);\n"
                           "padding: 2px;\n"
                           "}\n"
                           "QWidget#Form{\n"
                           "background-color: rgb(56, 60, 72);\n"
                           "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setStyleSheet("QWidget{\n"
                                  "border-top: 2px solid rgb(19, 148, 207);\n"
                                  "border-bottom: 2px solid rgb(19, 148, 207);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover{\n"
                                  "border-top: none;\n"
                                  "border-bottom: none;\n"
                                  "border-right: 2px solid rgb(85, 170, 255);\n"
                                  "border-left: 2px solid rgb(85, 170, 255);\n"
                                  "background-color: rgba(233, 247, 255, 180);\n"
                                  "padding: 0px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.vegaBtn = QtWidgets.QPushButton(parent=self.widget)
        self.vegaBtn.setMinimumSize(QtCore.QSize(0, 35))
        self.vegaBtn.setObjectName("vegaBtn")
        self.horizontalLayout_2.addWidget(self.vegaBtn)
        self.selectBtn = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.selectBtn.setObjectName("selectBtn")
        self.horizontalLayout_2.addWidget(self.selectBtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
                                    "background: transparent;\n"
                                    "}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.model = QtGui.QFileSystemModel()
        self.model.setRootPath("")

        self.treeView = QtWidgets.QTreeView(parent=self.widget_2)
        self.treeView.setStyleSheet("border: 2px solid rgb(19, 148, 207);")
        self.treeView.setObjectName("treeView")
        self.treeView.setModel(self.model)
        self.treeView.setRootIndex(self.model.index(""))
        self.treeView.setColumnWidth(0, 250)
        self.horizontalLayout.addWidget(self.treeView)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def goDesktop(self):
        self.treeView.setRootIndex(self.model.index(""))

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))
        self.vegaBtn.setText(_translate("Form", "Move To Vega Current Folder"))
        self.selectBtn.setText(_translate("Form", "Select"))

    def mousePressEvent(self, event: QtGui.QMouseEvent):
        if event.button() == QtCore.Qt.MouseButton.LeftButton:
            self.dragging = True
            self.moving_offset = event.pos().toPointF().toPoint()
            event.accept()

    def mouseReleaseEvent(self, event: QtGui.QMouseEvent):
        if event.button() == QtCore.Qt.MouseButton.LeftButton:
            self.dragging = False
            event.accept()

    def mouseMoveEvent(self, event: QtGui.QMouseEvent):
        if self.dragging:  #
            self.move(self.pos().x().real + (event.pos().x().real - self.moving_offset.x().real),
                      self.pos().y().real + (event.pos().y().real - self.moving_offset.y().real))
            event.accept()

    def closeEvent(self, event: QtGui.QCloseEvent):
        self.browserWidget.inputpath.setText(self.treeView.selectedIndexes())
        print(self.treeView.selectedIndexes())