# Form implementation generated from reading ui file '.\topbar.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys

class Ui_Topbar(object):
    def setupUi(self, Topbar):
        Topbar.setObjectName("Topbar")
        Topbar.resize(744, 43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Topbar.sizePolicy().hasHeightForWidth())
        Topbar.setSizePolicy(sizePolicy)
        Topbar.setMinimumSize(QtCore.QSize(300, 43))
        Topbar.setMaximumSize(QtCore.QSize(16777215, 43))
        Topbar.setStyleSheet("QWidget#Topbar{\n"
"background-color: rgb(34, 37, 44);\n"
"border-radius: 10px;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Topbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Topbar)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout")
        self.ToggleSlideMenuBtn = QtWidgets.QPushButton(parent=self.widget)
        self.ToggleSlideMenuBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.ToggleSlideMenuBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.ToggleSlideMenuBtn.setStyleSheet("QPushButton#ToggleSlideMenuBtn{\n"
"border-radius: 10px;\n"
"    image: url(:/icons_w/C:/Users/izanp/Downloads/Feather_white/menu.svg);\n"
"background-color: rgb(34, 37, 44);\n"
"}\n"
"\n"
"\n"
"QPushButton#ToggleSlideMenuBtn:hover{\n"
"    \n"
"    background-color: rgb(102, 111, 132);\n"
"}")
        self.ToggleSlideMenuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons_w/res/Feather_white/menu.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ToggleSlideMenuBtn.setIcon(icon)
        self.ToggleSlideMenuBtn.setObjectName("ToggleSlideMenuBtn")
        self.horizontalLayout_3.addWidget(self.ToggleSlideMenuBtn)
        self.user_person_img = QtWidgets.QLabel(parent=self.widget)
        self.user_person_img.setText("")
        self.user_person_img.setObjectName("user_person_img")
        self.horizontalLayout_3.addWidget(self.user_person_img)
        self.user_name = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("color: rgb(0, 170, 255);")
        self.user_name.setObjectName("user_name")
        self.horizontalLayout_3.addWidget(self.user_name)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_2 = QtWidgets.QWidget(parent=Topbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expandBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expandBtn.sizePolicy().hasHeightForWidth())
        self.expandBtn.setSizePolicy(sizePolicy)
        self.expandBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.expandBtn.setStyleSheet("QPushButton#expandBtn{\n"
"background-color: rgb(38, 225, 54);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#expandBtn:hover{\n"
"background-color: rgb(137, 225, 121);\n"
"}\n"
"\n"
"QPushButton#expandBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.expandBtn.setText("")
        self.expandBtn.setObjectName("expandBtn")
        self.horizontalLayout_2.addWidget(self.expandBtn)
        self.minBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minBtn.sizePolicy().hasHeightForWidth())
        self.minBtn.setSizePolicy(sizePolicy)
        self.minBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.minBtn.setStyleSheet("QPushButton#minBtn{\n"
"background-color: rgb(255, 157, 44);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#minBtn:hover{\n"
"background-color: rgb(255, 180, 89);\n"
"}\n"
"\n"
"QPushButton#minBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.minBtn.setText("")
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_2.addWidget(self.minBtn)
        self.closeBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.closeBtn.setStyleSheet("QPushButton#closeBtn{\n"
"background-color: rgb(255, 53, 53);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#closeBtn:hover{\n"
"background-color: rgb(255, 105, 105);\n"
"}\n"
"\n"
"QPushButton#closeBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.closeBtn.setText("")
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.horizontalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(Topbar)
        QtCore.QMetaObject.connectSlotsByName(Topbar)

    def retranslateUi(self, Topbar):
        _translate = QtCore.QCoreApplication.translate
        Topbar.setWindowTitle(_translate("Topbar", "Form"))
        self.user_name.setText(_translate("Topbar", "PERSON NAME"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Topbar()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())