# Form implementation generated from reading ui file '.\vega_UI.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 931)
        MainWindow.setStyleSheet("QWidget#TheWidget{\n"
"border-image: url(:/images/space.jpg);\n"
"background-color: rgba(190, 190, 190, 190);\n"
"border-radius: 10px;\n"
"backdrop-filter: blur(60px);\n"
"}")
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.TheWidget = QtWidgets.QWidget(parent=MainWindow)
        self.TheWidget.setObjectName("TheWidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.TheWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 946, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topbar = QtWidgets.QWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.topbar.sizePolicy().hasHeightForWidth())
        self.topbar.setSizePolicy(sizePolicy)
        self.topbar.setMinimumSize(QtCore.QSize(94, 0))
        self.topbar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.topbar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.topbar.setStyleSheet("background-color: rgb(34, 37, 44);\n"
"border-radius: 10px;\n"
"")
        self.topbar.setObjectName("topbar")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.topbar)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(820, 0, 121, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expandBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expandBtn.sizePolicy().hasHeightForWidth())
        self.expandBtn.setSizePolicy(sizePolicy)
        self.expandBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.expandBtn.setStyleSheet("QPushButton#expandBtn{\n"
"background-color: rgb(38, 225, 54);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#expandBtn:hover{\n"
"background-color: rgb(137, 225, 121);\n"
"}\n"
"\n"
"QPushButton#expandBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.expandBtn.setText("")
        self.expandBtn.setObjectName("expandBtn")
        self.horizontalLayout_2.addWidget(self.expandBtn)
        self.minBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minBtn.sizePolicy().hasHeightForWidth())
        self.minBtn.setSizePolicy(sizePolicy)
        self.minBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.minBtn.setStyleSheet("QPushButton#minBtn{\n"
"background-color: rgb(255, 157, 44);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#minBtn:hover{\n"
"background-color: rgb(255, 180, 89);\n"
"}\n"
"\n"
"QPushButton#minBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.minBtn.setText("")
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_2.addWidget(self.minBtn)
        self.closeBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setMaximumSize(QtCore.QSize(18, 18))
        self.closeBtn.setStyleSheet("QPushButton#closeBtn{\n"
"background-color: rgb(255, 53, 53);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton#closeBtn:hover{\n"
"background-color: rgb(255, 105, 105);\n"
"}\n"
"\n"
"QPushButton#closeBtn:pressed{\n"
"background-color: rgb(61, 148, 225);\n"
"}")
        self.closeBtn.setText("")
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.verticalLayout_2.addWidget(self.topbar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(240, 120))
        self.widget_2.setMaximumSize(QtCore.QSize(240, 120))
        self.widget_2.setStyleSheet("background-color: rgb(34, 37, 44);\n"
"border-top-left-radius: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.sidebar = QtWidgets.QWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QtCore.QSize(240, 300))
        self.sidebar.setMaximumSize(QtCore.QSize(240, 16777215))
        self.sidebar.setStyleSheet("background-color: rgb(56, 60, 72);\n"
"")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout.addWidget(self.sidebar)
        self.widget = QtWidgets.QWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(240, 120))
        self.widget.setMaximumSize(QtCore.QSize(240, 120))
        self.widget.setStyleSheet("background-color: rgb(34, 37, 44);\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.canvas = QtWidgets.QWidget(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setMinimumSize(QtCore.QSize(700, 540))
        self.canvas.setStyleSheet("background-color: rgb(232, 236, 247);\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;")
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MainWindow)
        self.expandBtn.clicked.connect(MainWindow.showMaximized) # type: ignore
        self.minBtn.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.closeBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #DRAGGING
        self.dragging = False
        self.offset = QtCore.QPoint()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TheWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>centWidg</p></body></html>"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())